### ISSUE TITLE
Expose Block Type and Category data on blocked results page

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#106]
In the /status/url JSON, the results stanza for each ISP tested now includes a blocktype, block category and  site category.  It would be good to incorporate this into the results page.

The format of the results JSON is described on the ORG wiki (https://wiki.openrightsgroup.org/wiki/Censorship_Monitoring_Project_API#GET_.2Fstatus.2Furl).  
- Categories (toplevel) is the list of DMOZ categories that apply to the URL.
- [isp]/category - category information from the ISP's blocked response page.  May tell is what blocking category the site fell into (such as adult content, weapons, drugs)
- [isp]/blocktype - PARENTAL or COPYRIGHT, indicating which of an ISP's blocking systems stopped the page or what type of rule was matched by the probe.

**Comment by dantheta** [comment]
This relates to #67

**Comment by sr-murthy** [comment]
Am a newbie to cmp but am happy to start working on this.

**Comment by graphiclunarkid** [comment]
Hi @sr-murthy, welcome to the project, and thanks for offering to get involved!

I'm afraid it's going to be difficult for you to work on this particular issue right now because the changes need to be made to our front-end website. That's served via a Modx instance for which we don't have a development server right now. The only instance is our live server to which we restrict access to staff only.

If you're looking for a way to contribute, the "24pullrequests" label will give you a set of issues I think would be accessible to newcomers, which you can see here:

https://github.com/openrightsgroup/cmp-issues/issues?q=is%3Aopen+is%3Aissue+label%3A24PullRequests

**Comment by dantheta** [comment]
I've added the site category (parsed from the ISP response page, where they support it).   I had to make the text quite small to preserve the layout, but it still works.  We may need to update the explanatory text a bit.

**Comment by dantheta** [comment]
The category data doesn't look so good on the page: The DMOZ categories require multiple levels to give them context, and there isn't a lot of room for such a large amount of text.  This ticket should probably be parked until the results page layout is being revised.

**Comment by dantheta** [comment]
These are present in the new frontend.
