### ISSUE TITLE
Make results-table population more obviously "live"

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#110]
It would be neat to wait until the results page has rendered before starting to populate the table.

The landline tests return more quickly than the page takes to render so they appear in the table immediately. Mobile results then start updating or appearing maybe 10 seconds later. This is surprising to the user.

An artificial delay would both highlight the fact that tests are live and show off the live-update mechanism. It would also make inserting or updating rows seem less surprising when late results arrive.

**Comment by Polarisation** [comment]
I can see this being tricky to get right. One problem is that the results appear quite far down on the page, typically below the fold. The user typically has to scroll down to see the results table, and since we do not know when the user will do this, delaying by a constant time would not be effective. It might be possible to detect whether the table has become visible on-screen and then start populating the table.

However the whole idea of artificially delaying results until we choose to show them makes me uneasy... this could potentially confuse the user more than current behavior. I'd like to consider alternatives for improving the presentation.

**Comment by Polarisation** [comment]
And here's an alternative...

We would pre-fill the table with a blank row for each ISP we are expecting a result for, then we can display a small loading indicator (spinning gif) per row for each probe we are waiting for. When each result comes in, the row for that ISP would be updated: loading indicator removed, and status and timestamp added in place.

To do this we would need make changes not only to the JavaScript, but to the initial page. The initial page would need:
- A row for each ISP even if no results have been returned yet.
- A time stamp for the submission. This can be hidden from the user, but we would need it to be available in cases where a URL has previous existing results, to determine if a new result has been returned since the last submission.

**Comment by graphiclunarkid** [comment]
I like it :+1: 

We have already considered rendering historical results differently in #105 so this would tie in quite nicely with that.

We can probably pull a dynamic list of ISPs where we have live probes from somewhere. I know we have more ISPs in the database than we display in the result so there must be a filter defined somewhere.

If submission time-stamps aren't available in the API data already they should be pretty easy to add!

**Comment by edjw** [comment]
This is happening now

**Comment by dantheta** [comment]
Yep.
