### ISSUE TITLE
Integrate with YourNextMP API

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#115]
YourNextMP is building an API for information about election candidates at http://yournextmp.mysociety.org

e.g. http://yournextmp.mysociety.org/person/4582

Are we able to pull the websites from this and run them through checks on blocked.org.uk?

**Comment by hyl** [comment]
Just been looking into this: PopIt is based on elasticsearch, so the following (paginated) result _should_ bring back all the candidates with URL fields: http://yournextmp.popit.mysociety.org/api/v0.1/search/persons?q=_exists_:homepage_url

I'm guessing it's just a case getting all the homepage_url values from those JSON responses, filtering out any blank values, then feeding them into the Blocked API?

**Comment by webal** [comment]
Hi @hyl, that url doesn't seem to return all candidates I couldn't find this guy (http://yournextmp.com/person/1195) in the json returned. If it's paginated do you know the format of subsequent pages - it would be much easier than having to find all constituencies then querying each one. thanks

**Comment by webal** [comment]
ignore that found this line in json `"next_url": "http://yournextmp.popit.mysociety.org/api/v0.1/search/persons?page=2",` - duh

**Comment by webal** [comment]
I've got a basic version of this working, it's in a branch of the main middleware repo (https://github.com/openrightsgroup/Blocking-Middleware/tree/ger-mp-homepages).

Currently if a URL is not already in the system it will add it and tag it as 'nextmp' for the source. (don't forget to update the enum in urls table to add 'nextmp' for source column - code at top of parse_mps file).

I'm thinking it would be useful to be able to mark all MP websites as such, I'm not sure the best way to do this - so suggestions welcome. Otherwise I guess a separate table that has the urlID in it to keep a record. Is it worth saving any other data - MP name or constituency? 

Also I'm guessing it'd be useful to pull out all blocked results from this source, so I'll have a look at that when I get a chance.

**Comment by graphiclunarkid** [comment]
This is great work, you two - thanks!

@webal, would you like to send a pull request? I'd love to hear @dantheta's thoughts on the code. I'll try to get it running too (good excuse for me to sort out my local Vagrant configuration!)

**Comment by webal** [comment]
I was chatting to Dan over the weekend - he gave me a hand with a couple of issues. He's going to double check and then merge that branch. 
If you pull it down and checkout that branch it should run fine on vagrant VM - I used the VM to develop it.
The next job will be to be able to pull out the results of blocked sites from this source.

**Comment by graphiclunarkid** [comment]
Now that openrightsgroup/Blocking-Middleware#63 is merged I'm closing this issue in favour of #113
