### ISSUE TITLE
TalkTalk probe not detecting court-ordered blocks

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#120]
( Follow up to #24 )

The following have court orders for blocking, but currently show as ok for the TalkTalk filters.

https://www.blocked.org.uk/results?url=http://megashare.info
https://www.blocked.org.uk/results?url=http://viooz.co
https://www.blocked.org.uk/results?url=http://watch32.com
https://www.blocked.org.uk/results?url=http://zmovie.co

See http://wiki.451unavailable.org.uk/wiki/UK/HC13D05470

**Comment by dantheta** [comment]
Fixed and deployed in config file update.

When originally tested the talktalk URLs seemed to only redirect to 
http://www.siteblocked.org/piratebay.html.  

They've since added more pages, which the config rule wasn't catching.  

The content might be an interesting thing to mine and record, since it gives the date and petitioner for the court order.  The blocked page is viewable outside TalkTalk's network.
