### ISSUE TITLE
Show category notes for a URL on all network reports

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/cmp-issues#178]

**Comment by dantheta** [comment]
The category management functions now operate at the URL level instead of ISP report.  Effectively, the same category tab is shown no matter which ISP report you are viewing it from.

The comments have been changed to an append-log style, rather than having one value.  I've copied the data from the old field into the new table.

From the category tab, it is possible to:
* Suppress/reactivate a category mapping (internal or external)
* Add a new category mapping from the ORG category list
* Add a new category to the ORG category list and assign it to the current URL
* Add notes describing the reasoning for any of the above operations

It's also possible to just add notes without changing any categories.

The UI can be refined further (toggle checkboxes are a bit clunky), but it should be enough to keep moving forward for now.

**Comment by edjw** [comment]
Thanks Dan I think that's a nice solution
