### ISSUE TITLE
Unable to see category notes posted by other administrators

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#180]
Unless I am missing something, it would appear that the "category notes" field in the backend, found under "Review Categories", is one which is specific to myself and I cannot see notes added by other admins.

**Comment by edjw** [comment]
I can see your notes in Review Categories for this one:

https://www.blocked.org.uk/control/ispreports/BT/337/http://www.talkingdrugs.org


Might it be that you're not seeing notes by me because I added them in a particular ISP's report page and you're looking at a different ISP page for the same blocked URL? Dan is going to make sure notes for the same URL are available on all pages related to that URL later tonight

**Comment by alexhaydock** [comment]
Maybe I am mistaken then, but I thought I had remembered watching you enter notes for this one:

https://www.blocked.org.uk/control/ispreports/Sky/386/http://feeld.co

I cannot see any notes in the Review Categories section here.

If you didn't enter any then I can close this ticket since it's probably the case that I'm just not seeing any notes because none have been written.

**Comment by dantheta** [comment]
At the moment, the categorisation note (singular) is stored on the ISP 
report record (which is incorrect).  This is likely to change tonight, 
so it's probably best to add them sparingly until tomorrow.  The notes 
field is visible to all admins.

I'm thinking that it will be moved to the url-category mapping record, 
so you'll get one note for each category that is added/removed.

Related: #178

**Comment by alexhaydock** [comment]
Thanks Dan. That sounds ideal and answers a ticket I was about to create just now. :+1:

To confirm, the notes will be visible from any of the ISP reports for a particular domain and not just per-ISP?

**Comment by JimKillock** [comment]
In general, I think review information, flags, notes etc, should probably be added and then superseded rather than edited.

EG, a reviewer supplies a note, on a specific date, then a new one is added if needed.

The same applies for categorisations and judgements whether an ISP policy is applied correctly.

This is because all observations can be valid at a particular date and time, but may not be in the future. It’s worth stating clearly when the observation was deemed valid, and then stating at what date it became invalid.

This is what we found with the copyright blocks also. Things change, and we should record when we noticed they had changed.

**Comment by dantheta** [comment]
On 2019-02-11 16:22, Alex Haydock wrote:
> Thanks Dan. That sounds ideal and answers a ticket I was about to
> create just now. :+1:
> 
> To confirm, the notes will be visible from any of the ISP reports for
> a particular domain and not just per-ISP?

That's right (for the categorisation notes) - the per-ISP bit was an 
accidental error.

**Comment by dantheta** [comment]
This is fixed (or at least, made a lot clearer in #178)
