### ISSUE TITLE
Review information: add child-related flag

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#234]
Add flag: "Site is aimed at or relevant to children"

I think this is easier than categorising for children, as the sites are across multiple topics (advice, charities, music, etc).

We can the produce a report on sites categorised within this group.

**Comment by dantheta** [comment]
I think having an "Aimed at children" category could work - multiple categories can be assigned to a URL, so reporting on the intersection of the children's category and other categories is definitely possible.

**Comment by JimKillock** [comment]
We've in the event assigned sites to one category only, so that the figures add up neatly!

An alternative would be to assign categories (of any kind perhaps) in a priority order?

Then your tables could ignore secondary categories, or not, as we liked.

**Comment by dantheta** [comment]
That sounds like a good plan.  We don't currently have anywhere to keep URL flags other than tags.  

In the short term, I'll get the system to treat the first ORG category added to a URL as the primary and all of the others as secondary (for the purposes of keeping consistent totals).  Later on we can add UI that allows the primary category to be selected.

The URL category reports can have extra columns added so that the totals for primary categories are displayed alongside the total for all categories.

**Comment by dantheta** [comment]
This one's going to take a bit longer to put together, I'm afraid.  Many apologies.

**Comment by JimKillock** [comment]
No worries; for me the plan should be that we try to get this done and shoehorn it into the report / launch, as it is just one stat; but for now we are handing over the report without this.

**Comment by dantheta** [comment]
Additional ORG categories can now be added to a URL in the ISP reports screen.

Only one of the ORG categories can be marked "primary"; on the URL categories page there is a column for primary and all categories, so that the report is still able to show a consistent total even if more categories are added to URLs.

**Comment by dantheta** [comment]
The "Aimed at children" category can now be created and added to sites as a secondary category.

**Comment by edjw** [comment]
Can this be closed?

**Comment by dantheta** [comment]
Yep, I think so.
