### ISSUE TITLE
Number of Unblocked sites being miscounted in Saved Lists

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/cmp-issues#240]
In the [Saved Lists page](https://www.blocked.org.uk/lists) and on individual list pages [like this one](https://www.blocked.org.uk/list/Weddings), sites are being shown as Unblocked when they're not.

[This site report](https://www.blocked.org.uk/site/http://3valleymvc.org.uk) for example shows the site is still blocked, but [the list it's in](https://www.blocked.org.uk/list/Weddings) shows it as Unblocked.

The numbers of Unblocked URLs on [the Saved Lists page](https://www.blocked.org.uk/lists) seem to be wrong as a result.

**Comment by alexhaydock** [comment]
This is probably as a result of openrightsgroup/blocked-org-uk#378 still producing buggy behaviour.

**Comment by dantheta** [comment]
I've updated the refresh program to check all public lists and re-run all of them, rather than waiting for the schedule job to work its way through.  All of the public list items I've checked now match the unblocked badge on the list page.

The method for deriving the unblocked URLs figure on the saved lists page has also changed as a result of openrightsgroup/blocked-org-uk#376.

**Comment by dantheta** [comment]
This seems to be working consistently.
