### ISSUE TITLE
Bug: "See another block site" link

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#244]
This is leading to the report for the *same* site's report, rather than a random blocked-on-list website report.

**Comment by dantheta** [comment]
Not quite -

The /next/ URL does contain the name of the current entry.  It's a 
little counter-intuitive, but when a user visits that, the site looks up 
the *next* item in the list and displays that.

Example:

Frontpage shows carmenperez.org in the "help unblock this site" region.  
The "try another" link points to /next/www.carmenperez.org.

When the user follows that link, they are shown the site report page for 
(in this case) www.HcLTransport.org.uk.

This is done because the feed of sites to show in the list is 
pre-generated (so that large numbers of frontpage visits don't swamp the 
database with searching for a new frontpage site to show, and so that 
concurrent visitors definitely get shown a different site).

The /next/ handler is written this way so that large numbers of visitors 
to the frontpage don't eat all of the pregenerated feed items without 
clicking on any.

The URL could be formatted as /next?after=carmenperez.org, which might 
make it slightly less misleading.

**Comment by JimKillock** [comment]
Great, so long as it works that's fine for now!

**Comment by dantheta** [comment]
New URL is now in use.
