### ISSUE TITLE
Results page OG bug

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#55]
On the results page for URLs, currently the OpenGraph URL meta rage is broken:

```
        <meta property="og:url" name="twitter:url" content="https://new.blocked.org.uk/results">
```

which derives from the page ID [[*id]] in MODx. This URL needs to read

```
        <meta property="og:url" name="twitter:url" content="https://new.blocked.org.uk/results?url=http://www.example.com"> 
```

else the OpenGraph protocol observes the results page redirect back to the home page.

**Comment by graphiclunarkid** [comment]
Possibly because the query string doesn't form part of the MODx page ID? We can fix this using a new chunk just for the blocked site. If we do that, I suggest we use the existing chunk on all pages except /results, which will also let us tailor the OG description field for the results pages.

The existing chunk uses the page [[_longtitle]] as its content unless that's blank, in which case it uses the page title. I haven't checked whether all the [[_longtitle]]s are fit for use in this way... perhaps we should do that!

**Comment by dantheta** [comment]
This is taken care of in the new frontend.
