### ISSUE TITLE
Produce two overall stats, one for “defaults” and one for “any”, displayed on the front page; 

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#73]
this would explain the differing results

**Comment by NetworksAreMadeOfString** [comment]
IMHO any registered and DNS resolvable URL is implicitly "allowed".

This goes back to my point a while ago that we should "pre-crawl" URLs from the webserver (which is known to be unblocked and can gather HTTP return code, mime type, content length etc) before submitting to the probes.

**Comment by graphiclunarkid** [comment]
I think what Jim means is that there should be two stats counters: one saying X% blocked on at least on network at default settings; and a second saying Y% blocked on at least one network across all results (including opt-in non-default categories). The expectation would be Y > X.

**Comment by NetworksAreMadeOfString** [comment]
Ah, I see.

My bad.

**Comment by JimKillock** [comment]
Again, I'm thinking it's for Dan and apologies for giving you more work!

**Comment by dantheta** [comment]
There's a new element in the /status/stats response called blocked_sites_detected_default_filter, which contains the count of sites which are blocked at the default filter levels for any ISP.  The existing elements are left unchanged, so that the count doesn't suddenly change before frontend and copywriters are ready.  

The /status/stats documentation on the wiki has been updated, and the code has been tested and deployed.  Over to you, frontend!

**Comment by JimKillock** [comment]
@mkillock can you help us implement this on the front end?

**Comment by mkillock** [comment]
I've added a new placeholder [[!+blocked_sites_detected_default_filter]] which has the requested value. This isn't being used anywhere on the page yet, partly because it sounds like we need another bit of javascript that draws the animated percentage graph.

By the way, the JSON response seems to come back as: 

{"success":true,"stats":{"blocked_sites_detected":24669,"blocked_sites_detected_default_f":12610,"urls_reported":127855,"urls_tested":127841}}

Note the shortened "blocked_sites_detected_default_f" - is this something PHP has decoded incorrectly?

**Comment by mkillock** [comment]
No it seems that is what comes back in the response, judging by pasting in the query into a webrowser

**Comment by dantheta** [comment]
My bad, the database column for the key is too short.  fixing that shortly!

**Comment by dantheta** [comment]
Right, fixed now.  Will update the DB docs when I get home.

**Comment by mkillock** [comment]
Thanks! I've also updated GetURLStats snippet to work with the lengthened name.

@webal - can you do the 2nd percentage graph? Assuming that's what @JimKillock wants?

**Comment by JimKillock** [comment]
@webal that would be great if you can help :)

**Comment by JimKillock** [comment]
OK, I hacked @webal's scripts to produce two graphs, not great presentationally however - pushes the form very low.

**Comment by JimKillock** [comment]
Kind of done for now I think - thanks all!
