### ISSUE TITLE
Drive headline statistic on front page from reference set of URLs

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#91]
When we added 70,000 charity websites to the dataset, most of these were not blocked, so that reduced the "percentage of blocked sites" we were displaying by about half. However this is not representative since charity sites are much less likely to be blocked. Likewise, if we were to add a database of 70,000 porn sites the statistics would be artificially high.

The "percentage of blocked sites" statistics on the front page should reflect a neutral reference-set of URLs so that it always gives a representative headline figure that we and others can quote.

**Comment by dantheta** [comment]
I've tried out applying the alexa 100k filter to produce the headline stats, but it also affects the "Tests pending" and "Sites Tested" figure, fixing these at 0 and 100000 respectively.  The percentage figures for strict and default settings do get better though.

The "tests pending" and "sites" checked figures are driven from the urls_reported and urls_tested fields in the Stats API response.

Is it worth providing an additional  URL count in that API response, so that the blocked percentages can be reported based on the alexa 100k, and the "sites tested" can be based on the total number of URLs in the system?

Sample api response:

```
(
    [urls_reported] => 197657
    [urls_tested] => 197638
    [blocked_sites_sample_size] => 100000 // new value for calculating percentages
    [blocked_sites_detected] => 19493
    [blocked_sites_detected_default_filter] => 9439
)
```

The frontpage could then be updated to show "19493 19% sites blocked by strict settings" (based on 19493 / 100000), and the sites tested counter could carry on incrementing

The ISP stats page also highlights where we have incomplete results for the alexa 100k on a given ISP.  We can prioritise getting this set completed when the mobile lines are available again.

I'm going to roll back these two changes for now.

**Comment by dantheta** [comment]
Sorry - ignore that last rollback request.  I'm going to roll out the blocked_sites_sample_size additional field, and maybe frontend can be updated to use that for the blocked percentages?  That way the "sites tested" figure can carry on growing on the front page.

**Comment by dantheta** [comment]
OK - all ready for the frontend change, if you'd like to go ahead.

**Comment by graphiclunarkid** [comment]
Finally got round to implementing this on the front end! Have changed the homepage layout a bit too. All comments welcome!

**Comment by dantheta** [comment]
Ah wonderful!  I was thinking of this issue today in the lead-up to importing DMOZ.  Adding another million URLs might have distorted the original figure quite a bit!

I think it looks great.
