### ISSUE TITLE
Admin interface to force retesting per URL/network

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#92]
Would it be possible to make a priority retest of a URL on a per-network basis, possibly just for authenticated users.

example
https://twitter.com/boagworld/status/492577452217364480
suggests that EE are blocking linkedin.com

https://www.blocked.org.uk/results?url=http://www.linkedin.com
doesn't show a block for EE, but last test was 2014-07-05 - so I'd like to request a recheck on that network.

**Comment by dantheta** [comment]
Ideally the queues are kept empty, so all requests are processed as early as
possible with no need for prioritization. 

We're having trouble with EE at the moment because the mobile internet
connection keeps going down and the queues are backlogged.  O2 and Vodafone
are unable to maintain a steady connection too.

From manual checking, there's no block on linkedin at the moment. Sorry
about that.

**Comment by graphiclunarkid** [comment]
I agree with @dantheta. If we want to retest a URL we just submit it via the front page and results are returned in a few seconds (a couple of refreshes might be required for slow networks).

**Comment by graphiclunarkid** [comment]
Rate-limiting by URL means my comment above is no longer true so we need to provide a separate feature for running a live re-check.
